In [1]:
!pip install geopy

Requirement already satisfied: geopy in c:\users\bbukulin\anaconda3\lib\site-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in c:\users\bbukulin\anaconda3\lib\site-packages (from geopy) (2.0)

In [2]:
import pandas as pd
from geopy.geocoders import Nominatim
import time

In [3]:
data = pd.read_csv('cleaned_qatar_airways_reviews.csv')

In [4]:
geolocator = Nominatim(user_agent="geoapiExercises")

In [5]:
def geocode_location(location):
    try:
        return geolocator.geocode(location)
    except:
        return None

In [6]:
# Geokodiranje jedinstvenih lokacija
# Geokodiranje jedinstvenih lokacija
unique_locations = set(data['From'].tolist() + data['To'].tolist())
if 'Direct' not in unique_locations:
    unique_locations.update(data[data['Via'] != 'Direct']['Via'].tolist())
location_coords = {}

for location in unique_locations:
    geocoded = geocode_location(location)
    if geocoded:
        location_coords[location] = (geocoded.latitude, geocoded.longitude)
    time.sleep(1)  # Pauza kako bi se izbjegao preveliki broj zahtjeva u kratkom vremenu

In [7]:
# Dodavanje koordinata u originalne podatke
data['FromLat'] = data['From'].apply(lambda x: location_coords[x][0] if x in location_coords else None)
data['FromLon'] = data['From'].apply(lambda x: location_coords[x][1] if x in location_coords else None)
data['ToLat'] = data['To'].apply(lambda x: location_coords[x][0] if x in location_coords else None)
data['ToLon'] = data['To'].apply(lambda x: location_coords[x][1] if x in location_coords else None)
data['ViaLat'] = data['Via'].apply(lambda x: location_coords[x][0] if x in location_coords and x != 'Direct' else None)
data['ViaLon'] = data['Via'].apply(lambda x: location_coords[x][1] if x in location_coords and x != 'Direct' else None)

In [8]:
data.to_csv('cleaned_qatar_airways_reviews_with_coords_corrected.csv', index=False)

In [9]:
data.head()

,Date Published,Rating,Max Rating,Author,Country,Title,Review Body,Type Of Traveller,Seat Type,Date Flown,...,Via,To,Verified,Recommended,FromLat,FromLon,ToLat,ToLon,ViaLat,ViaLon
0,2024-02-29,1.0,10.0,Wayne Burgess,Australia,"""no attempt to address our complaint""",I have sent 5 emails and have only received ...,Business,Economy Class,November 2023,...,Direct,Perth,1.0,no,NaN,NaN,-31.955893,115.860585,NaN,NaN
1,2024-02-25,10.0,10.0,Alwaleed Althani,Qatar,“I hope they update the A380”,We flew on probably the first A380 the airlin...,Couple Leisure,First Class,February 2024,...,Direct,London,1.0,Yes,NaN,NaN,51.507446,-0.127765,NaN,NaN
2,2024-02-22,7.0,10.0,W Warnock,United Kingdom,"""I’d rate them maybe 7/10""","Service was ok, pretty good on my aisle and ...",Couple Leisure,Business Class,February 2024,...,Direct,Doha,1.0,no,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-02-20,10.0,10.0,Qandeel Ahtasham,United Kingdom,"""remarkable experience""",12th February 2024 From check in to get onboa...,Family Leisure,Business Class,February 2024,...,Direct,London,1.0,Yes,NaN,NaN,51.507446,-0.127765,NaN,NaN
4,2024-02-20,10.0,10.0,N Foster,United States,“incredible service”,"Remarkable experience. Great tasting food, l...",Family Leisure,Economy Class,February 2024,...,Direct,San Francisco,0.0,Yes,28.613895,77.209006,37.779259,-122.419329,NaN,NaN